export type {
  IdummyInput as ICtDummyInput,
  IdummyOutput as ICtDummyOutput,
} from "./service-soap.types";
export {
  IautorizarComprobanteInput,
  IautorizarComprobanteOutput,
  IconsultarUltimoComprobanteAutorizadoInput,
  IconsultarUltimoComprobanteAutorizadoOutput,
  IconsultarComprobanteTipoPVentaNroInput,
  IconsultarComprobanteTipoPVentaNroOutput,
  IconsultarPuntosVentaInput,
  IconsultarPuntosVentaOutput,
  IconsultarTiposComprobantesInput,
  IconsultarTiposComprobantesOutput,
  IconsultarMonedasInput,
  IconsultarMonedasOutput,
  IconsultarCotizacionInput,
  IconsultarCotizacionOutput,
  IconsultarTiposDocumentoInput,
  IconsultarTiposDocumentoOutput,
  IconsultarPaisesInput,
  IconsultarPaisesOutput,
  IconsultarCUITsPaisesInput,
  IconsultarCUITsPaisesOutput,
  IconsultarTiposIVAInput,
  IconsultarTiposIVAOutput,
  IconsultarTiposDatosAdicionalesInput,
  IconsultarTiposDatosAdicionalesOutput,
  IconsultarTiposTributoInput,
  IconsultarTiposTributoOutput,
  IconsultarCondicionesIVAInput,
  IconsultarCondicionesIVAOutput,
  IconsultarNovedadesInput,
  IconsultarNovedadesOutput,
  IconsultarFormasPagoInput,
  IconsultarFormasPagoOutput,
  IconsultarTiposItemInput,
  IconsultarTiposItemOutput,
  IconsultarCodigosItemTurismoInput,
  IconsultarCodigosItemTurismoOutput,
  IconsultarRelacionEmisorReceptorInput,
  IconsultarRelacionEmisorReceptorOutput,
  IconsultarTiposCuentaInput,
  IconsultarTiposCuentaOutput,
  IconsultarTiposTarjetaInput,
  IconsultarTiposTarjetaOutput,
  CTServiceSOAPTypes,
} from "./service-soap.types";
